spring:
  application:
    name: spring-lab

server:
  port: 8080

app:
  owner: Pak Dmitriy
  group: IT1CCO-2503IS
  mail:
    from: no-reply@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true
  locale:
    default-locale: ru
    supported:
      - ru
      - kk
      - en

logging:
  level:
    kz.iitu: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops,conditions